spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/${REALM_NAME}

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${FRONTEND_URL}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
            maxAge: 3600
        add-to-simple-url-handler-mapping: true

      routes:
        - id: profile_service
          uri: ${PROFILE_URL}
          predicates:
            - Path= ${PROFILE_PATH}
        - id: reports_Service
          uri: ${REPORTS_URL}
          predicates:
            - Path= ${REPORTS_PATH}
          filters:
            - StripPrefix=1
        - id: advertising_service
          uri: ${ADVERTISING_URL}
          predicates:
            - Path= ${ADVERTISING_PATH}
          filters:
            - StripPrefix=1
        - id: recipe_service
          uri: ${RECIPE_URL}
          predicates:
            - Path= ${RECIPE_PATH}
          filters:
            - StripPrefix=1
        - id: strapi_service
          uri: ${STRAPI_URL}
          predicates:
            - Path= ${STRAPI_PATH}
          filters:
            - StripPrefix=1
        - id: recommendations_service
          uri: ${RECOMMENDATIONS_URL}
          predicates:
            - Path= ${RECOMMENDATIONS_PATH}
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: ${AUTH_URL}
          predicates:
            - Path= ${AUTH_PATH}
          filters:
            - StripPrefix=1

server:
  port: ${API_PORT}

logging:
  level:
    org.springframework.cloud.gateway: ${DEBUG}
    org.springframework.security: ${DEBUG}
    org.springframework.security.oauth2: ${DEBUG}
